name = "Dwether Mc"
author = "Datta_The_Proto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0293dcf82132bfbbd230b9f1603e2cff2ee8d707a42e321896276f2b0017c2e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
