name = "Dwether Mc"
author = "Datta_The_Proto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5a9ae480a128b5ee799c6592663519ea73216a42c08c3901cf533e874c1283e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
