name = "Dwether Mc"
author = "Datta_The_Proto"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0979e6b89ce8a93d5edf38259110001b5b0c073058d0143ae113af40037c27e2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
